import {useState} from "react";import Header from "../components/layout/Header";import Card from "../components/common/Card";import SearchAccount from "../components/account/SearchAccount";import AccountDetails from "../components/account/AccountDetails";import LinkedAccounts from "../components/account/LinkedAccounts";import CsvUpload from "../components/bulk/CsvUpload";import AccountList from "../components/bulk/AccountList";import ProcessingSummary from "../components/bulk/ProcessingSummary";import HowItWorks from "../components/information/HowItWorks";import {validateAccount,delinkAccount} from "../services/accountApi";import {parseAccountsCsv,downloadResultCsv,downloadTemplateCsv} from "../utils/csv";import {validateAccountId} from "../utils/validation";
const wait=ms=>new Promise(r=>setTimeout(r,ms));const row=id=>({accountId:id,loginId:null,loginType:null,status:"Pending",error:null,children:[]});
export default function DeLinkAccounts(){const[searchId,setSearchId]=useState("10000012345"),[found,setFound]=useState(null),[searchError,setSearchError]=useState(""),[searching,setSearching]=useState(false),[file,setFile]=useState(null),[error,setError]=useState(""),[accounts,setAccounts]=useState([]),[selected,setSelected]=useState(new Set()),[expanded,setExpanded]=useState(new Set()),[processing,setProcessing]=useState(false);
async function validateMany(ids){for(const id of ids){setAccounts(x=>x.map(a=>a.accountId===id?{...a,status:"Validating",error:null}:a));const r=await validateAccount(id);setAccounts(x=>x.map(a=>a.accountId===id?{...a,...r,loginId:r.loginId,loginType:r.loginType,children:(r.children||[]).map(c=>({...c,status:"Validated",selected:false,error:null})),status:r.exists?"Validated":"Failed",error:r.exists?null:r.error}:a))}}
async function upload(e){const f=e.target.files?.[0];if(!f)return;setError("");try{const r=await parseAccountsCsv(f);setFile({name:f.name,count:r.accounts.length,size:`${(f.size/1024).toFixed(1)} KB`});setAccounts(r.accounts.map(row));setSelected(new Set());await validateMany(r.accounts)}catch(err){setFile(null);setAccounts([]);setError(err.message)}}
function toggle(id){setSelected(s=>{const n=new Set(s);n.has(id)?n.delete(id):n.add(id);return n})}
function selectAll(v){setSelected(v?new Set(accounts.filter(a=>a.status!=="Failed").map(a=>a.accountId)):new Set())}
async function bulk(){if(processing)return;const ids=accounts.filter(a=>selected.has(a.accountId)&&a.status==="Validated").map(a=>a.accountId);if(!ids.length)return;setProcessing(true);for(const id of ids){setAccounts(x=>x.map(a=>a.accountId===id?{...a,status:"Processing"}:a));const r=await delinkAccount(id);setAccounts(x=>x.map(a=>a.accountId===id?{...a,status:r.success?"De-linked":"Failed",error:r.success?null:r.error,children:r.success?a.children.map(c=>({...c,status:"De-linked"})):a.children}:a));await wait(80)}setProcessing(false)}
async function search(){const e=validateAccountId(searchId);if(e){setSearchError(e);setFound(null);return}setSearching(true);setSearchError("");try{const r=await validateAccount(searchId.trim());if(!r.exists){setFound(null);setSearchError("Account not found on backend.");}else setFound(r)}finally{setSearching(false)}}
async function refresh(){if(!accounts.length||processing)return;setAccounts(x=>x.map(a=>({...a,status:"Pending",error:null})));await validateMany(accounts.map(a=>a.accountId))}
async function individual(){if(!found?.linkedAccountId)return;setSearching(true);const r=await delinkAccount(found.accountId);if(r.success)setFound(x=>({...x,linkedAccountId:null,linkedOn:null}));else setSearchError(r.error);setSearching(false)}
return <div><Header/><main className="mx-auto max-w-[1470px] px-5 py-5 lg:px-8"><div className="mb-5"><h1 className="text-[27px] font-semibold tracking-[-.03em]">De-Link Accounts (Bulk)</h1><p className="mt-1 text-sm text-slate-500">Upload a CSV file to de-link multiple accounts</p></div><div className="grid items-start gap-5 xl:grid-cols-[440px_minmax(0,1fr)]"><div className="space-y-5"><SearchAccount value={searchId} onChange={e=>{setSearchId(e.target.value);setSearchError("")}} onSearch={search} error={searchError} found={!!found} loading={searching}/>{found?<><AccountDetails account={found}/><LinkedAccounts account={found} onDelink={individual} disabled={searching}/></>:<Card className="p-5"><p className="text-sm text-slate-500">Search for an account to view its details.</p></Card>}</div><div className="space-y-5"><CsvUpload info={file} error={error} onUpload={upload} onRemove={()=>{setFile(null);setAccounts([]);setSelected(new Set())}} onTemplate={downloadTemplateCsv} disabled={processing}/>{accounts.length?<AccountList accounts={accounts} selected={selected} toggle={toggle} selectAll={selectAll} expanded={expanded} expand={id=>setExpanded(s=>{const n=new Set(s);n.has(id)?n.delete(id):n.add(id);return n})} processing={processing} refresh={refresh} bulk={bulk} download={()=>downloadResultCsv(accounts)}/>:<Card className="flex min-h-[260px] items-center justify-center p-8"><div className="text-center"><p className="text-sm font-medium">No accounts uploaded yet</p><p className="mt-1 text-xs text-slate-500">Upload a CSV containing an Account ID column to begin.</p></div></Card>}</div></div><ProcessingSummary accounts={accounts}/><HowItWorks/></main></div>}